homepage:
    path: /
    controller: App\Controller\HomepageController::index
login:
    path: /login
    controller: App\Controller\AuthenticationController::login
logout:
    path: /logout
    controller: App\Controller\AuthenticationController::logout
admin:
    path: /admin
    controller: App\Controller\AdminController::index
